# Generated by Django 5.2.17 on 2026-08-16 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_type', models.CharField(choices=[('contains', 'Description contains'), ('exact', 'Description is exactly'), ('starts_with', 'Description starts with'), ('regex', 'Description matches regex'), ('upi_vpa', 'UPI VPA is')], default='contains', max_length=16)),
                ('pattern', models.CharField(max_length=500)),
                ('origin', models.CharField(choices=[('user', 'Created by the user'), ('learned', 'Learned from a recategorisation'), ('builtin', 'Shipped with the app')], default='user', max_length=16)),
                ('priority', models.IntegerField(default=0, help_text='Higher wins. Defaults by origin; set explicitly to override.')),
                ('is_active', models.BooleanField(default=True)),
                ('match_count', models.PositiveIntegerField(default=0, help_text='How many transactions this rule has categorised. Surfaces dead rules.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='categories.category')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.household')),
            ],
            options={
                'ordering': ['-priority', 'id'],
                'indexes': [models.Index(fields=['household', 'is_active', '-priority'], name='rules_categ_househo_88fdb0_idx')],
                'constraints': [models.UniqueConstraint(fields=('household', 'match_type', 'pattern'), name='unique_rule_per_household')],
            },
        ),
    ]
