# Generated by Django 5.2.17 on 2026-08-16 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('depth', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('colour', models.CharField(blank=True, help_text='Hex colour for charts, e.g. #1f6f4a.', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('is_income', models.BooleanField(default=False, help_text='Income rather than spending. Kept out of expense totals and budgets.')),
                ('is_system', models.BooleanField(default=False, help_text='Seeded by the app. Users may rename these but not delete them.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.household')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category')),
                ('root', models.ForeignKey(blank=True, editable=False, help_text='Top-level ancestor. Denormalised so roll-ups are a single join.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descendants', to='categories.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['household', 'root'], name='categories__househo_51d14b_idx'), models.Index(fields=['household', 'parent'], name='categories__househo_1e4dc7_idx')],
                'constraints': [models.UniqueConstraint(fields=('household', 'parent', 'name'), name='unique_category_name_per_parent'), models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('household', 'name'), name='unique_root_category_name')],
            },
        ),
    ]
