# Generated by Django 5.2.17 on 2026-08-16 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='What the user calls it, e.g. "HDFC Salary" or "ICICI Amazon Pay".', max_length=100)),
                ('kind', models.CharField(choices=[('bank', 'Bank account'), ('credit_card', 'Credit card')], max_length=16)),
                ('bank_slug', models.CharField(blank=True, help_text="Parser slug this source's statements use, e.g. 'hdfc'.", max_length=40)),
                ('account_hint', models.CharField(blank=True, help_text='Masked account or card tail, e.g. XXXXXXXX1234. Never the full number.', max_length=32)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('is_archived', models.BooleanField(default=False, help_text='Closed accounts stay for their history but are hidden from new uploads.')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.household')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['household', 'is_archived'], name='sources_sou_househo_69b084_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('account_hint', ''), _negated=True), fields=('household', 'bank_slug', 'account_hint'), name='unique_source_per_account_hint')],
            },
        ),
    ]
