# Generated by Django 5.2.17 on 2026-08-16 19:10

import apps.statements.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.statements.models.statement_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('bank_slug', models.CharField(blank=True, max_length=40)),
                ('statement_kind', models.CharField(blank=True, max_length=16)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('transaction_count', models.PositiveIntegerField(default=0, help_text='Transactions created by this upload.')),
                ('duplicate_count', models.PositiveIntegerField(default=0, help_text='Rows already present from an earlier upload, skipped rather than duplicated.')),
                ('error_message', models.TextField(blank=True, help_text='Shown to the user when parsing fails, so it must be actionable.')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.household')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements', to='sources.source')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['household', '-created_at'], name='statements__househo_427084_idx')],
            },
        ),
    ]
