# Generated by Django 5.2.17 on 2026-08-16 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
        ('sources', '0001_initial'),
        ('statements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('txn_date', models.DateField(db_index=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(help_text='The narration exactly as the bank printed it.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('is_categorised_by_user', models.BooleanField(default=False, help_text='Set when a person picks the category, so re-running the rules never overrides it.')),
                ('dedupe_hash', models.CharField(editable=False, max_length=64)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='categories.category')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.household')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='sources.source')),
                ('statement', models.ForeignKey(blank=True, help_text='The upload this arrived in. Kept for provenance; nulled if it is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='statements.statement')),
            ],
            options={
                'ordering': ['-txn_date', '-id'],
                'indexes': [models.Index(fields=['household', '-txn_date'], name='transaction_househo_6afe1a_idx'), models.Index(fields=['household', 'category'], name='transaction_househo_6d8e83_idx'), models.Index(fields=['source', '-txn_date'], name='transaction_source__8d57e0_idx')],
                'constraints': [models.UniqueConstraint(fields=('household', 'dedupe_hash'), name='unique_transaction_per_household')],
            },
        ),
    ]
