# Generated by Django 5.2.17 on 2026-08-17 20:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField(help_text='Any date in the month; stored as the 1st.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The limit for this category this month, as a positive number.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('note', models.CharField(blank=True, max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='categories.category')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.household')),
            ],
            options={
                'ordering': ['-month', 'category__sort_order', 'category__name'],
                'indexes': [models.Index(fields=['household', 'month'], name='budgets_bud_househo_95b74c_idx')],
                'constraints': [models.UniqueConstraint(fields=('household', 'category', 'month'), name='unique_budget_per_category_month')],
            },
        ),
    ]
